### ISSUE TITLE
`docker/check` incorrectly handle registry variable

### ISSUE THREAD

**Issue by superflyxxi** [CircleCI-Public/docker-orb#123]
### Orb version
2.1.0

### What happened
```
- docker/check:
          registry: ${CACHE_REGISTRY}
          docker-username: CACHE_USERNAME
          docker-password: CACHE_PASSWORD
```
The ${CACHE_REGISTRY} used to evaluate to the value. Now it remains as the literal and cannot use 2.1.0 orb.

Orb source 2.1.0
```
echo "${!PARAM_DOCKER_PASSWORD}" | docker login -u
        "${!PARAM_DOCKER_USERNAME}" --password-stdin "$PARAM_REGISTRY"
```

Orb source 2.0.5 (notice the `<< parameters.registry >>` vs converting to an env variable.
```
echo "$<<parameters.docker-password>>" \
          | docker login -u "$<<parameters.docker-username>>" \
              --password-stdin <<parameters.registry>>
```
### Expected behavior
The env variables value should be used and not the literal variable name.
