### ISSUE TITLE
`extra_build_args` wraps everything in single quotes

### ISSUE THREAD

**Issue by dhuckins** [CircleCI-Public/docker-orb#125]
### Orb version

2.1.1

### What happened

am trying to use `extra_build_args` to pass in env vars, but they keep getting wrapped in single quotes, preventing the env var from being expanded
example:
```yaml
# .circleci/config.yml
# have tried every quoting combination I can think of
extra_build_args: '--build-arg NPM_TOKEN=$NPM_TOKEN'
```
the command being run is
```sh
docker build --build-arg 'NPM_TOKEN=$NPM_TOKEN' ...
```
bash does not evaluate in single quotes, so the literal string `$NPM_TOKEN` is being passed to docker instead of the actual value

### Expected behavior

the command should be
```sh
docker build --build-arg NPM_TOKEN=$NPM_TOKEN
```
OR wrap in double quotes so we can use env vars
```sh
docker build --build-arg "NPM_TOKEN=$NPM_TOKEN"
```

**Comment by laupow** [comment]
This bug blocks us from using the latest version of the orb. The use case is mounting secrets with ` --secret` in the build step.

```yaml
- docker/build:
    image: org/image
    path: <<parameters.dockerfile-path>>
    docker-context: <<parameters.dockerfile-context>>
    tag: "workflow-$CIRCLE_WORKFLOW_ID"
    extra_build_args: --secret id=npmrc,src=${DOCKER_BUILD_SECRET_PATH}/.npmrc
```

dockerfile:
```dockerfile
FROM alpine
RUN --mount=type=secret,id=npmrc,dst=/root/.npmrc test -s /root/.npmrc
```

My guess is the regression popped up in https://github.com/CircleCI-Public/docker-orb/pull/115/files. We reverted to 2.0.5 and our tests pass.
