### ISSUE TITLE
`cache_from` parameter not being used when `use-buildkit: true`

### ISSUE THREAD

**Issue by jenny-miggin** [CircleCI-Public/docker-orb#127]
### Orb version

2.1.1

### What happened

When `use-buildkit: true`, and `cache_from:` parameter is populated (in order to pull an image to use as a cache during the `docker/build` command), the image is pulled but _not_ used as a cache during Docker build ([example](https://app.circleci.com/pipelines/github/jenny-miggin/dlc-orb-test/64/workflows/12f47c70-110b-4d95-94e1-0356705699c1/jobs/117))

When `use-buildkit: false`, or not present at all, the pulled image is used as a cache successfully ([example](https://app.circleci.com/pipelines/github/jenny-miggin/dlc-orb-test/65/workflows/eda394ce-e580-4245-a090-a5f9fb824331/jobs/118))

When `cache_from` parameter is populated with an envvar, the image is not used as a cache ([example](https://app.circleci.com/pipelines/github/jenny-miggin/dlc-orb-test/66/workflows/6251cfd1-7bf6-49d6-bfe6-44666dc0651e/jobs/119))

### Expected behavior
When `use-buildkit: true`, an image should be able to be used as a cache to build another image e.g. the below config should allow for the use of the pulled image as a cache:

```
      - docker/build:
          cache_from: $AWS_ECR_ACCOUNT_URL/my-app:latest
          image: $AWS_ECR_ACCOUNT_URL/my-app
          tag: latest
          use-buildkit: true
```
with this in the `Docker build` output:

```
Step 2/3 : RUN apt update && apt install -y nginx
 ---> Using cache
 ---> 12345layer
```
