### ISSUE TITLE
Integrate buildx

### ISSUE THREAD

**Issue by zigarn** [CircleCI-Public/docker-orb#134]
Any plan to allow users to build with buildx?

**Comment by gavinclarkeuk** [comment]
@brivu any updates on this?

**Comment by gavinclarkeuk** [comment]
@brivu any updates on this?

**Comment by brivu** [comment]
Hey @gavinclarkeuk and @zigarn, 

I'm currently working on fixing issues for this orb at the moment but will circle back to add `buildx` capabilities. 

We just want to be thoughtful in how we approach this i.e specifying different contexts, using `buildx` with Docker Layer Caching and more. 

I'll do my best to have this done in the next couple of months.

Best, 
Brian

**Comment by filip-aipl** [comment]
hey @brivu! 
Any update on the buildx? Is there any chance to use maybe dev version with buildx integrated?

**Comment by brivu** [comment]
Hey Everyone, 

We're wrapping up the quarter here in the next couple of weeks and there aren't any plans to have this released. I'm hoping we'll prioritize this next quarter and will bring your feedback back to the team as we plan. 

The good news is we have a fix in place to get `DLC` working with `buildx`, which was blocking us from implementing this in the first place. 

Thanks for your patience here!

Best, 
Brian

**Comment by gavinclarkeuk** [comment]
@brivu any updates, its been a couple of months

**Comment by gavinclarkeuk** [comment]
@brivu any updates?

**Comment by troyharvey** [comment]
@EricRibeiro Here's the job we are using that we would like to replace with the orb. There are two key features we're missing:

* `buildx build --platform` for building ARM and AMD
* `buildx build --secret` for preventing secrets from leaking into the image from CI through environment variables

```
jobs:
  docker-buildx-push:
  # A job that can build/push ARM and AMD Docker images.
  # TODO: Use the Docker orb once buildx multi-arch support is added.
  # @see https://github.com/CircleCI-Public/docker-orb/issues/134
  # @see https://stackoverflow.com/questions/73938529/docker-multi-platform-builds-extremely-slow-for-arm64-on-gitlab-ci
  # @see https://gist.github.com/jruiz94/f4b7bbb67e0ff7c71e9c582c7673af0c
    docker:
      - image: cimg/base:current
    parameters:
      arch:
        enum:
          - arm
          - amd
        type: enum
      platform:
        enum:
          - linux/arm64/v8
          - linux/amd64
        type: enum
      resource-class:
        enum:
          - large
          - arm.large
        type: enum
      tag:
        type: string
      poetry-version:
        type: string
        default: *poetry-version
    resource_class: << parameters.resource-class >>
    steps:
      - setup_remote_docker
      - checkout
      - dockerhub-login
      - run: |
          export DOCKER_CLI_EXPERIMENTAL=enabled
          docker buildx create --name multiarch --driver docker-container --use
          docker buildx build \
            --platform << parameters.platform >> \
            --secret id=POETRY_HTTP_BASIC_REDACTED_PASSWORD,env=redacted \
            --build-arg POETRY_VERSION=<< parameters.poetry-version >> \
            --build-arg BUILDKIT_INLINE_CACHE=1 \
            --push \
            --cache-to type=registry,ref=redacted/$CIRCLE_PROJECT_REPONAME:cache-<< parameters.arch >>,mode=max \
            --cache-from type=registry,ref=redacted/$CIRCLE_PROJECT_REPONAME:cache-<< parameters.arch >> \
            --tag redacted/$CIRCLE_PROJECT_REPONAME:<< parameters.tag >>-<< parameters.arch >> .
```

```
      - docker-buildx-push:
          # Build the candidate image using an ARM64 machine
          name: docker-buildx-push-arm
          platform: linux/arm64/v8
          arch: arm
          resource-class: arm.large
          tag: *tag

      - docker-buildx-push:
          # Build the candidate image using an AMD64 machine
          name: docker-buildx-push-amd
          platform: linux/amd64
          arch: amd
          resource-class: large
          tag: *tag
```
