### ISSUE TITLE
Job Publish is failing with "invalid reference format: repository name must be lowercase"

### ISSUE THREAD

**Issue by ssplatt** [CircleCI-Public/docker-orb#136]
### Orb version

2.1.2

### What happened

build stage passes, push stage fails with "invalid reference format: repository name must be lowercase", apparently unable to parse the parameters or environment variables properly.

```
default:
  jobs:
    - docker/publish:
          executor: docker/docker
          use-remote-docker: true
          image: $CIRCLE_PROJECT_USERNAME/pycqa-tools
          path: '3.7'
          docker-context: '3.7/.'
          update-description: true
          tag: 3.7,3.7-$CIRCLE_SHA1,3.7-$CIRCLE_BUILD_NUM
          requires:
            - docker/hadolint
          context: dockerhub
          filters:
            branches:
              only:
                - master
```

### Expected behavior

containers build and push. SSHing in and setting the environment variables by hand and running the script commands by hand works.

```
circleci@fb09f749d290:~/project$ PARAM_TAG=3.7,3.7-$CIRCLE_SHA1,3.7-$CIRCLE_BUILD_NUM
circleci@fb09f749d290:~/project$ echo $PARAM_TAG
3.7,3.7-6db1361431e5eff56a35842cc48f6a6754600c7f,3.7-462
circleci@fb09f749d290:~/project$ IFS="," read -ra DOCKER_TAGS <<< "$PARAM_TAG"
circleci@fb09f749d290:~/project$ PARAM_REGISTRY=docker.io
circleci@fb09f749d290:~/project$ PARAM_IMAGE=$CIRCLE_PROJECT_USERNAME/pycqa-tools
circleci@fb09f749d290:~/project$ for docker_tag in "${DOCKER_TAGS[@]}"; do
>   tag=$(eval echo "$docker_tag")
>   docker push "$PARAM_REGISTRY"/"$PARAM_IMAGE":"$tag"
> done
The push refers to a repository [docker.io/ssplatt/pycqa-tools]
87602ec4b676: Pushed
d9fe01159fea: Pushed
91ab80281724: Layer already exists
dfb2aa1ea2ab: Layer already exists
b456e73bba2a: Layer already exists
12a7221db5c8: Layer already exists
c44b6ed055fe: Layer already exists
a88ee98d25a2: Layer already exists
2484ba8523f6: Layer already exists
37dc959d0ca6: Layer already exists
cae87053165d: Layer already exists
9f54eef41275: Layer already exists
3.7: digest: sha256:28d43a860d06adfdcfec186ac7ce7574b9992cbf2bdaeffe85d76282587843e4 size: 2859
The push refers to a repository [docker.io/ssplatt/pycqa-tools]
87602ec4b676: Layer already exists
d9fe01159fea: Layer already exists
91ab80281724: Layer already exists
dfb2aa1ea2ab: Layer already exists
b456e73bba2a: Layer already exists
12a7221db5c8: Layer already exists
c44b6ed055fe: Layer already exists
a88ee98d25a2: Layer already exists
2484ba8523f6: Layer already exists
37dc959d0ca6: Layer already exists
cae87053165d: Layer already exists
9f54eef41275: Layer already exists
3.7-6db1361431e5eff56a35842cc48f6a6754600c7f: digest: sha256:28d43a860d06adfdcfec186ac7ce7574b9992cbf2bdaeffe85d76282587843e4 size: 2859
The push refers to a repository [docker.io/ssplatt/pycqa-tools]
87602ec4b676: Layer already exists
d9fe01159fea: Layer already exists
91ab80281724: Layer already exists
dfb2aa1ea2ab: Layer already exists
b456e73bba2a: Layer already exists
12a7221db5c8: Layer already exists
c44b6ed055fe: Layer already exists
a88ee98d25a2: Layer already exists
2484ba8523f6: Layer already exists
37dc959d0ca6: Layer already exists
cae87053165d: Layer already exists
9f54eef41275: Layer already exists
3.7-462: digest: sha256:28d43a860d06adfdcfec186ac7ce7574b9992cbf2bdaeffe85d76282587843e4 size: 2859
```
