### ISSUE TITLE
[FEATURE] Support env var substitution for extra_build_args or document limitation

### ISSUE THREAD

**Issue by tboddyspargo** [CircleCI-Public/docker-orb#137]
This is related to #135 which also deals with support (or lack thereof) for variable expansion.

### Description
The parameter for `extra_build_args` (for example) doesn't support environment variable expansion and are expanded as string literals. _(Furthermore, documentation doesn't call out this limitation)._

https://github.com/CircleCI-Public/docker-orb/blob/aa06f5779dbefb2e49c3da8fea7da6da86115e0e/src/scripts/build.sh#L55

In contrast, environment variables _ARE_ expanded by the `eval` function when used with the `tag` parameter of `docker/build`:

https://github.com/CircleCI-Public/docker-orb/blob/aa06f5779dbefb2e49c3da8fea7da6da86115e0e/src/scripts/build.sh#L16-L22

### Orb version
2.1.1

### What happened
**Config used**
```yaml
      - docker/build:
          step-name: Build Image
          image: image-name
          path: ./test
          # ${CIRCLE_PULL_REQUEST//*\//} extracts the PR number from the end of the URL.
          tag: pr${CIRCLE_PULL_REQUEST//*\//}-<<pipeline.number>>
          registry: ecr.repo
          docker-context: ./test
          use-buildkit: true
          extra_build_args: "--build-arg tag=pr${CIRCLE_PULL_REQUEST//*\//}-<<pipeline.number>>"
```

> **NOTE:** In this example, the Dockerfile for `image-name` uses a base image of `FROM ecr.repo/base-image:$tag` where `tag` is configurable via a build argument.

**Result**
```
+ docker build --file=./test/Dockerfile --tag=ecr.repo/image-name:pr21287-66010 --build-arg 'tag=pr${CIRCLE_PULL_REQUEST//*\//}-66010' --progress=plain ./test
#1 [internal] load build definition from Dockerfile
#1 sha256:eb014c755523a3e17edaa5ba45823475c0d79e84080bf471329e433bbba40d23
#1 transferring dockerfile: 799B done
#1 DONE 0.0s

#2 [internal] load .dockerignore
#2 sha256:9a26e70af2b9fa49abfba33982469cde5b1291f497ea89d4136ec92ad02a8531
#2 transferring context: 2B done
#2 DONE 0.0s
failed to solve with frontend dockerfile.v0: failed to create LLB definition: failed to parse stage name "ecr.repo/base-image:pr${CIRCLE_PULL_REQUEST//*\\//}-66010": invalid reference format
```

> **NOTE:** Notice how the value of `--tag=...` in the `docker build` command is expanded correctly, but the value of `--build-arg tag=...` was not expanded. This is despite the fact that the value provided to both `string` parameters was identical.

### Expected behavior
I'd like to request that `extra_build_args` get similar treatment to `tag` to support variable expansion within the `docker/build` command. This would allow uses can take advantage of [built-in variables](https://circleci.com/docs/variables#built-in-environment-variables) like `$CIRCLE_PULL_REQUEST` (as well as custom ones) in their build args for images.

While my immediate need is limited to the `extra_build_args` parameter of the `docker/build` command, it's worth considering consistent handling for all parameters in all commands.

However, if there are significant concerns with supporting env var expansion similar to `tag` for certain parameters, then I think it's worth calling out that limitation because it is not inherently obvious (nor expected) from the parameters `type` or `description` as they are currently written.
