### ISSUE TITLE
Setting multiple tags with a dynamic tag fails

### ISSUE THREAD

**Issue by ryanwi** [CircleCI-Public/docker-orb#152]
### Orb version

2.1.3

### What happened

When attempting to set multiple, dynamic, tags, the job fails because it is treating the tags as one.

With config.yml snippet:
```
jobs:
  build-staging-image:
    machine:
      image: ubuntu-2204:current
      docker_layer_caching: true
    steps:
      - checkout
      - run: echo "staging-$(git show -s --format="%cs" | tr -d '-')-${CIRCLE_SHA1:0:8}-${CIRCLE_BUILD_NUM},circlecitest" > .tags
      - run: cat .tags
      - docker/build:
          dockerfile: provisioning/dockerfiles/rails/Dockerfile
          use-buildkit: true
          tag: "$(cat .tags)"
      - docker/push:
          tag: "$(cat .tags)"
```

results in an error:

```
+ docker build --file=./provisioning/dockerfiles/rails/Dockerfile --tag=docker.io/org/image:staging-20220919-884cc0c3-430,circlecitest --progress=plain .
invalid argument "docker.io/org/image:staging-20220919-884cc0c3-430,circlecitest" for "-t, --tag" flag: invalid reference format
See 'docker build --help'.

Exited with code exit status 125
CircleCI received exit code 125
```

### Expected behavior

Ideally it would treat the tags as separate and produce:

```
+ docker build --file=./provisioning/dockerfiles/rails/Dockerfile --tag=docker.io/org/image:2022-09-19-6c777ef9c7b518208b6698e4f974fc7535b43927 --tag=docker.io/org/image:circlecitest --progress=plain .
```

**Comment by ryanwi** [comment]
If there is an alternative, or recommended, way to set multiple tags that include a dynamic way, that would help too.

**Comment by ryanwi** [comment]
Tried to narrow down to bash issue, but it is working on my test so far

```
IFS=","
bash-3.2$ cat .tags
staging-20220919,staging
bash-3.2$ read -ra tags <<< "$(cat .tags)"
bash-3.2$ echo "${#tags[@]}"
2
bash-3.2$ for tag in "${tags[@]}"; do echo "$tag"; done
staging-20220919
staging
```

**Comment by eddiewebb** [comment]
@ryanwi - this looks like an issue with interpolation.  

Using a command (not value) as the parameter adds a layer of evaluation we dont handle currently, meaning the literal value `"$(cat .tags)"` is what get's passed to the script.

So at the point the For LOOP is tokenizing on the comma , - there is not comma, the value is literally "$(cat .tags)", a single token and that finally get's executed when printed as part of single tag argument because the final EVAL statement in buiuld.sh

Here is a rough proxy to the flow:

```
IFS=","
# files contain list of tags needed, as csv text
echo "staging-20220919-bec4c0da-436,circlecitest" > .tags
#platform sets var to your provided  parameter, BUT uninterpreted
`echo "export PARAM_TAG=\$(cat .tags)" `

#script read it as the command
read -ra tags <<< "$PARAM_TAG"
echo "${#tags[@]}"
for tag in "${tags[@]}"; do   #only single token, the command
    echo "$tag"; 
    if [ -z "$docker_arg" ]; then
      docker_arg="--tag=\"$tag\"" #fcommand saved as single tag
    else
      docker_arg="$docker_arg --tag=\"$tag\""
    fi
done
DOCKER_TAGS_ARG="$(eval echo $docker_arg)" #command evaluated to text
IFS=" "
echo $DOCKER_TAGS_ARG  #result is 1 --tag with the full string from file.
```

Rather than trying to add layers of `eval` which can get nasty, I suggest we just explicitly support and check for the value being a file.

```
if [ -f "$PARAM_TAG" ]; then
   echo "Tag paramter matches file path, reading values from: $PARAM_TAG"
   PARAM_TAG=$(cat $PARAM_TAG)
fi
.. norma logic resumes
```


And then your config.yml would just need to be:

```
jobs:
  build-staging-image:
    machine:
      image: ubuntu-2204:current
      docker_layer_caching: true
    steps:
      - checkout
      - run: echo "staging-$(git show -s --format="%cs" | tr -d '-')-${CIRCLE_SHA1:0:8}-${CIRCLE_BUILD_NUM},circlecitest" > .tags
      - run: cat .tags
      - docker/build:
          dockerfile: provisioning/dockerfiles/rails/Dockerfile
          use-buildkit: true
          tag: .tags
      - docker/push:
          tag: .tags
```

**Comment by eddiewebb** [comment]
i.e.    (in build.sh)


```


# changes - build.sh checks for file
if [ -f "$PARAM_TAG" ]; then
   echo "Tag paramter matches file path, reading values from: $PARAM_TAG"
   PARAM_TAG=$(cat $PARAM_TAG)
fi

# normal logic resumes
IFS=","
read -ra tags <<< "$PARAM_TAG"
echo "${#tags[@]}"
for tag in "${tags[@]}"; do   #only single token, the command
    echo "$tag"; 
    if [ -z "$docker_arg" ]; then
      docker_arg="--tag=\"$tag\"" #fcommand saved as single tag
    else
      docker_arg="$docker_arg --tag=\"$tag\""
    fi
done
DOCKER_TAGS_ARG="$(eval echo $docker_arg)" #command evaluated to text
IFS=" "
echo $DOCKER_TAGS_ARG  #result is 1 --tag with the full string from file.

```

**Comment by ryanwi** [comment]
Thanks for clarifying. File sounds good to me. FWIW, the origin for this is migrating from drone which looks for a .tags file by default, when no value is specified for tags. (https://discourse.drone.io/t/using-custom-generated-tags-for-docker-images/1918/2

**Comment by tthayer** [comment]
This was working in the 2.0.3 orb and when I tried updating my pipeline to use 2.1.4 it throws the same error. We're populating the `tag` parameter with an environment variable generated by a prior step but I believe it's a similar issue.

**Comment by tthayer** [comment]
@brivu I ended up just leaving it at 2.0.3. Any new development is being applied to github action workflows.

**Comment by brivu** [comment]
Hey @ryanwi, @tthayer  and @eddiewebb, 

I'm running tests on version `2.2` of this orb and it seems to work fine. 

In the job below, I `echo` a couple of environment variables to a file called `.tag`. Then, I ran the `docker/build` command with `"$(cat .tag)"` as `tag` parameter, similar to @ryanwi's original example. 

```
test-build-with-args:
    docker:
      - image: cimg/base:current
    steps:
      - checkout
      - setup_remote_docker
      - run: echo "$CIRCLE_BUILD_NUM-$CIRCLE_SHA1" >> .tag
      - docker/build:
            dockerfile: test3.Dockerfile
            image: cpeorbtesting/docker-orb-test
            **tag: "$(cat .tag)"**
              extra_build_args: --build-arg COMMIT_HASH=$CIRCLE_SHA1
      - run: cat .tag
 ```

The build command ran successfully in the pipeline with the expected output: 
```
Successfully tagged cpeorbtesting/docker-orb-test:21466-*****************************`
```

Similarly with @tthayer's issue, I ran the `docker/build` command again and populated the `tag` parameter with environment variables, `$CIRCLE_BUILD_NUM-$CIRCLE_SHA1` to test and see if the variables would expand or be taken literally: 

```
  test-build-with-args:
    docker:
      - image: cimg/base:current
    steps:
      - checkout
      - setup_remote_docker
      - docker/build:
            dockerfile: test3.Dockerfile
            image: cpeorbtesting/docker-orb-test
            tag: $CIRCLE_BUILD_NUM-$CIRCLE_SHA1
            extra_build_args: --build-arg COMMIT_HASH=$CIRCLE_SHA1
```

Again, I was able to get a successful but with the expected output as well. 

I am going to close this issue for now but please reopen this issue if I am missing something. 

Best, 
Brian
