### ISSUE TITLE
Unable to install docker tools onto macos machine

### ISSUE THREAD

**Issue by rlam3** [CircleCI-Public/docker-orb#153]
### Orb version

2.1.3

### What happened
```
config.yml
orbs:
  macos: circleci/macos@2.3.2
  docker: circleci/docker@2.1.3

...
jobs:
    my-job:
    macos:
      xcode: '14.0.0'
    steps:
    - docker/install-docker-tools
...
workflow
    - my-job

```

```
#output from circleci
La**** version of Goss is v0.3.18
/bin/bash: line 46: /usr/local/bin/goss: cannot execute binary file
Something went wrong; the specified version of Goss could not be installed

Exited with code exit status 1

```

### Expected behavior

I expect that this docker-orb to be able to setup docker and spin up docker daemon in a macos machine executor
