### ISSUE TITLE
[FEATURE] Expand ENV variables in `cache_from` parameter value

### ISSUE THREAD

**Issue by jgarber623** [CircleCI-Public/docker-orb#166]
### Orb version

2.1.4

### What happened

Using the following abbreviated configuration in a job step:

```yaml
- docker/build:
    cache_from: us.gcr.io/${GOOGLE_PROJECT_ID}/xxx:${CIRCLE_BRANCH}-${CIRCLE_SHA1},us.gcr.io/${GOOGLE_PROJECT_ID}/xxx:${CIRCLE_BRANCH}-latest
    registry: us.gcr.io
    tag: ${CIRCLE_BRANCH}-${CIRCLE_SHA1},${CIRCLE_BRANCH}-latest
    use-buildkit: true
```

I'm seeing (correctly) that the `pull_images_from_cache` function pulls one of the requested images meaning that ENV variables are correctly expanded by that function. In subsequent log messages during the build process, I'm seeing messages like:

```txt
#4 importing cache manifest from us.gcr.io/${GOOGLE_PROJECT_ID}/xxx:${CIRCLE_BRANCH}-${CIRCLE_SHA1}
#4 sha256:xxx
#4 ERROR: invalid reference format: repository name must be lowercase
```

I did some digging and found #149 dealt with a similar issue with the `extra_build_args` parameter value. I _think_ a similar change to [these lines in `build.sh`](https://github.com/CircleCI-Public/docker-orb/blob/master/src/scripts/build.sh#L59-L61) would do the trick:

```sh
if [ -n "$PARAM_CACHE_FROM" ]; then
  cache_from="$(eval echo "$PARAM_CACHE_FROM")"
  build_args+=("--cache-from=$cache_from")
fi
```

### Expected behavior

ENV vars referenced in the `cache_from` parameter should properly expand.
