### ISSUE TITLE
`extra_build_args` fails with multiple args

### ISSUE THREAD

**Issue by jcuffney** [CircleCI-Public/docker-orb#174]
### Orb version

2.2.0

### What happened

```
      - docker/publish:
          image: <my-image>
          tag: <my-tag>
          # NOTE: multiple build args don't seem to work :(
          extra_build_args: "--build-arg VAR1=$VAR1 --build-arg VAR2=$VAR2"
```

yields the following error:

`/bin/bash: line 58: --build-arg: command not found`

I tested this both on the docker/publish job as well as the build / push commands and it behaves the same in both cases.  This appears to be a result of how build args are appended into the list in the orb source.

### Expected behavior

You should be able to use multiple build args as is described in the orb documentation

**Comment by brivu** [comment]
Hey @jcuffney, 

I just tested this with the same version of the orb with the following: 

 ```
      - docker/publish:
            name: publish-machine
            context: CPE-orb-docker-testing
            dockerfile: test.Dockerfile
            image: cpeorbtesting/docker-orb-test
            tag: $CIRCLE_BUILD_NUM-$CIRCLE_SHA1
            extra_build_args: --build-arg COMMIT_HASH=$CIRCLE_SHA1 --build-arg FTP_PROXY=http://40.50.60.5:4567
```

I was able run the `docker/publish` job successfully with no issues. The only difference is I did not surround the `extra_build_args` input with double quotes. 

I'm going to close this for now but if you're still having issues, can you please send me a sample of your config that's failing?

Thank you! 
Best, 
Brian
