### ISSUE TITLE
Image name used for executor image flake

### ISSUE THREAD

**Issue by Beanow** [CircleCI-Public/docker-orb#19]
### Orb version

`circleci/docker@0.5.13`

### What happened

On one of our builds: https://circleci.com/gh/sourcecred/sourcecred/2225#tests/containers/0
The executor image was incorrectly set to
```
  docker/publish-1:
    machine:
      docker_layer_caching: false
      image: sourcecred/sourcecred
```

Which is the name of the image to publish, not the VM image.
It hasn't done this in previous builds, such as https://circleci.com/gh/sourcecred/sourcecred/2227#config/containers/0
Where it uses the default (as intended)
```
  docker/publish-1:
    machine:
      docker_layer_caching: false
      image: ubuntu-1604:201903-01
```

### Expected behavior

The `image:` parameter shouldn't be passed on to the executor.
