### ISSUE TITLE
publish job fails with 3rd party registries

### ISSUE THREAD

**Issue by TimJones** [CircleCI-Public/docker-orb#2]
### Orb version
0.1.0

### What happened

If using a 3rd party repo (e.g. quay.io) the `publish` job will always fail.
The `build` command does not use the `registry` parameter so build an image the later `push` step cannot use.

### Expected behavior

`publish` job should be able to build & push to any 3rd party registry.

**Comment by TimJones** [comment]
As a workaround, you can use something like the following example:

```yaml
version: 2.1
orbs:
  docker: circleci/docker@0.1.0
workflows:
  build-and-publish-docker-image:
    jobs:
      - docker/publish:
          image: $CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME
          registry: my.docker.registry
          after_build:
            - run: docker tag $CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME:$CIRCLE_SHA1 my.docker.registry/$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME:$CIRCLE_SHA1
```

**NOTE** This uses the default `tag` value of `$CIRCLE_SHA1`. If you use the `tag`parameter you need to update the `after_build` step accordingly.
