### ISSUE TITLE
FR: Add support rewriting timestamps

### ISSUE THREAD

**Issue by thefirstofthe300** [CircleCI-Public/docker-orb#202]
We use the Docker orb for building and publishing some of our Docker images. We are working on reproducible builds and one of the things we need for our images is support for the SOURCE_DATE_EPOCH environment variable being set. We would also like to see the ability to rewrite timestamps inside the container as well.

https://reproducible-builds.org/docs/source-date-epoch/#dockerfile

**Comment by marboledacci** [comment]
What exactly is not already supported by this orb?
You can pass any extra flag to the build using `extra_build_args` and there are multiple ways to pass environment variables to a job https://circleci.com/docs/env-vars/#environment-variable-usage-options

**Comment by thefirstofthe300** [comment]
We are using the commit timestamp to set the SOURCE_DATE_EPOCH. I don't think  those methods linked would work simply because it requires setting the environment variable using an interpreted bash command.

**Comment by marboledacci** [comment]
Something like this would'n work for you?

```yaml
my-job:
    docker:
      - image: cimg/base:current
    steps:
      - checkout
      - run: |
           ./myScript.sh >> timestamp
           echo "export SOURCE_DATE_EPOCH=$(cat timestamp)" >> $BASH_ENV
      - docker/build:
          dockerfile: Dockerfile
          image: my-image
          tag: my-tag
```
