### ISSUE TITLE
Support for building/pushing images with multiple tags

### ISSUE THREAD

**Issue by jonadaly** [CircleCI-Public/docker-orb#36]
### Orb version
0.5.8

### What happened
The orb commands for build/push don't support multiple tags. For example, to use the docker/build command to create an image with 3 tags, you need to use three different steps:

```
version: 2.1
orbs: 
    docker: circleci/docker@0.5.8
jobs:
    my-job:
        steps:
            - docker/build:
                image: myrepo
                registry: myregistry
                tag: tag1
            - docker/build:
                image: myrepo
                registry: myregistry
                tag: tag2
            - docker/build:
                image: myrepo
                registry: myregistry
                tag: tag3
...
```

### Expected behavior
It would be great if we could build/push images with multiple tags in one step. Something like this:

```
version: 2.1
orbs: 
    docker: circleci/docker@0.5.8
jobs:
    my-job:
        steps:
            - docker/build:
                image: myrepo
                registry: myregistry
                tag: tag1,tag2,tag3
...
```

See, for example, the way this has been implemented for AWS: https://github.com/CircleCI-Public/aws-ecr-orb/blob/master/src/commands/build-image.yml#L51
