### ISSUE TITLE
build command ignores step-name parameter

### ISSUE THREAD

**Issue by wKovacs64** [CircleCI-Public/docker-orb#52]
### Orb version

0.5.20

### What happened

I set `step-name` in a `docker/build` step and the step still showed up as the default step name ("Docker build").

```yaml
jobs:
  test:
    steps:
      - docker/build:
          step-name: My custom step name
          image: whatever
```

<img width="179" alt="image" src="https://user-images.githubusercontent.com/1288694/73974698-0d3afd80-48e2-11ea-854a-9f9a1d628e81.png">

### Expected behavior

The step should be called "My custom step name" instead of the default step name.
