### ISSUE TITLE
hadolint Job's dockerfiles parameter does not work correctly

### ISSUE THREAD

**Issue by iwaiktos** [CircleCI-Public/docker-orb#54]
### Orb version

0.5.20

### What happened

When we specify multiple Dockerfile paths (relative to `~/project`) to the `dockerfiles` parameter, CircleCI says the second Dockerfile does not exist:

- In .circleci/config.yml:

```
workflows:
  version: 2
  some_job_name:
    jobs:
      - docker/hadolint:
          dockerfiles: ~/project/frontend/Dockerfile,~/project/worker/Dockerfile
```

- Result:

```
Running hadolint with the following options...


Success! /root/project/frontend/Dockerfile linted; no issues found
hadolint: ~/project/worker/Dockerfile: openBinaryFile: does not exist (No such file or directory)
```

### Expected behavior

Both Dockerfiles should be linted.

```
Running hadolint with the following options...


Success! /root/project/frontend/Dockerfile linted; no issues found
Success! /root/project/worker/Dockerfile linted; no issues found
```
