### ISSUE TITLE
Support Experimental Features

### ISSUE THREAD

**Issue by NFhbar** [CircleCI-Public/docker-orb#61]
### Orb version
circleci/docker@1.0.1

### What happened
Trying to build my image with the `--squash` command:

```yaml
      - docker/build:
          extra_build_args: '--squash'
          image: Dockerfile
          tag: 'mytag'
```

results in:

```
#!/bin/bash -eo pipefail
docker_tag_args=""

IFS="," read -ra DOCKER_TAGS <<< "${HOST}/node"
for tag in "${DOCKER_TAGS[@]}"; do
  docker_tag_args="$docker_tag_args -t docker.io/Dockerfile:${tag}"
done

docker build --squash \
  -f ./Dockerfile \
  $docker_tag_args \
  .
"--squash" is only supported on a Docker daemon with experimental features enabled

Exited with code exit status 1
CircleCI received exit code 1
```

### Expected behavior

Maybe include a flag to enable experimental features:

```yaml
      - docker/build:
          experimental: true
          extra_build_args: '--squash'
          image: Dockerfile
          tag: 'mytag'
```
