### ISSUE TITLE
How to use the executor parameters

### ISSUE THREAD

**Issue by TimJones** [CircleCI-Public/docker-orb#7]
### Orb version

0.5.0

### What happened

When trying to use a custom image for the docker executor (following https://circleci.com/orbs/registry/orb/circleci/docker#executors-docker & https://circleci.com/docs/2.0/reusing-config/#example-build-configuration-using-a-parameterized-executor) and needing to run a `npm` command before building the image I created the following job:

```yaml
    build-publish-docker-develop:
      - docker/publish:
          image: TimJones/myimage
          executor:
            docker/docker:
              image: circleci/node
              tag: 10.15
          use-remote-docker: true
          after_checkout:
            - restore_cache:
                key: npm-cache-{{ checksum "package.json" }}
            - run:
                name: Install dependencies
                command: yarn install
            - save_cache:
                key: npm-cache-{{ checksum "package.json" }}
                paths:
                  - ./node_modules
```
It fails with the following

```
#!/bin/sh -eo pipefail
# Error calling workflow: 'build-publish-docker-develop'
# Error calling job: 'docker/publish'
# Unexpected executor invocation format
# The value of `name` must be a string
# Examples of correct executor invocation:
#   executor: string-executor-name
#   executor: {name: string-executor-name}
#   executor: << parameters.executor-type-parameter >>
# 
# -------
# Warning: This configuration was auto-generated to show you the message above.
# Don't rerun this job. Rerunning will have no effect.
false
Exited with code 1
```

Obviously it is expecting something more like `executor: my-personal-executor`.
Is there a way to use the docker executor from the orb with the parameters as the documentation suggests, or do I have to create an executor separately?

### Expected behavior

To use the executor from the orb but with parameters supplied.

**Comment by TimJones** [comment]
After some more searching I found the answer in https://circleci.com/docs/2.0/reusing-config/#executor

For completeness the correct job should be:
```yaml
    build-publish-docker-develop:
      - docker/publish:
          image: TimJones/myimage
          executor:
            name: docker/docker:
            image: circleci/node
            tag: "10.15"
          use-remote-docker: true
          after_checkout:
            - restore_cache:
                key: npm-cache-{{ checksum "package.json" }}
            - run:
                name: Install dependencies
                command: yarn install
            - save_cache:
                key: npm-cache-{{ checksum "package.json" }}
                paths:
                  - ./node_modules
```
Maybe an example in the docs with this would be helpful?
