### ISSUE TITLE
Add parameter to save the built image locally

### ISSUE THREAD

**Issue by bfabio** [CircleCI-Public/docker-orb#77]
It would be nice to have a parameter to `publish` that saves the built image with `docker save`, so that you can easily share it to subsequent jobs via workspaces.

**Comment by EricRibeiro** [comment]
Hi @bfabio 👋 

Unless I got it wrong, wouldn't this be a matter of adding a step after the command in your job:

```
jobs:
  build-and-save:
    steps:
      - checkout
      - docker/build:
          ....
      - run:
           name: Run docker save
           command: docker save -o my_file.tar my_image:my_tag
      - store_artifacts:
           path: my_file.tar
```

It seems like overkill to have a parameter for a one-liner. I'll close the issue, but I can re-open it if you still think it has value and wants to discuss it.
